### ISSUE TITLE
ROOTで動くFFTを実装したい

### ISSUE THREAD

**Issue by LowToneVoice** [LowToneVoice/experiments#4]
## 目的

- 波長- (I_H-I_O)/(I_H+I_O) のグラフの振動位相を見るためにFFTが必要
- データはROOTファイルで導入されるので、できるだけそのままROOTファイルでFFTを済ませたい

## TODO

- [x] チュートリアル [https://root.cern/doc/master/FFT_8C.html](https://root.cern/doc/master/FFT_8C.html) を見る
- [x] oscillation_lambda.cppに実装
- [x] 振動数の適切な誤差決定方法を考察
- [ ] 誤差決定方法を実装
- [ ] サンプリング数の妥当性の検証 (cf. Remark, サプリング定理)

## Remark 

> for "real" frequencies you have to divide the x-axes range with the range of your function
y-axes has to be rescaled by a factor of 1/SQRT(n) to be right: this is not done automatically!

- サンプリング定理から、サンプリング周波数が信号の最大周波数の2倍以上にしなきゃいけないらしい。知らん。
- FFT後のx軸範囲を"the range of your function"で割らなきゃいけないらしい。
    - チュートリアル見てもよくわからない。横軸がおかしいことだけはわかる。
- FFT後のy軸はFFTヒストグラムのbin数nによって1/SQRT(n)倍にリスケールしなきゃいけないらしい。

**Comment by LowToneVoice** [comment]
## FFT x軸について

チュートリアルの写経から描画。
<img width="1055" alt="Screenshot 2024-01-11 at 19 08 44" src="https://github.com/LowToneVoice/experiments/assets/104371855/dc206e6b-00c0-48f5-81c9-2e11332df921">
画像1枚目はFFTさせるべき関数 $\sin x+\sin 2x+\sin (x/2) + 1$とそのヒストグラム。
2枚目はMAGモードでFFTしたもの。
おそらく波数-振幅なのだろうが、ホンマにFFTされてるか？

なお横軸最大値が25+1なのは
```
    Int_t n = 25;
    TH1D *hsin = new TH1D("hsin", "hsin", n + 1, 0, 4 * TMath::Pi());
    Double_t x;

    // Fill the histogram with function values
    for (Int_t i = 0; i <= n; i++)
    {
        x = (Double_t(i) / n) * (4 * TMath::Pi());
        hsin->SetBinContent(i + 1, fsin->Eval(x));
    }
```
としたから？
ただし本来nは実空間横軸0から4πをn分割してるので、フーリエ空間に出てくる筋合いはあまりないはず。

チュートリアルには
> NOTE: for "real" frequencies you have to divide the x-axes range with the range of your function (in this case 4*Pi);

と記載されているので、それに従って
`hm->GetXaxis()->SetLimits(0, 1.0 / (4 * TMath::Pi()));`
としたら
<img width="1055" alt="Screenshot 2024-01-11 at 19 02 34" src="https://github.com/LowToneVoice/experiments/assets/104371855/0996b5ba-f6cb-4f64-8204-dd66ac10b8f5">
となった。
横軸の数値が何を表しているのかは相変わらず不明。

binの並ぶ間隔から推察するに、左端のbinは順に $\sin0x, \sin(1/2 x), \sin1x, \sin2x$ に対応しているものと思われる。
では右端は？
なんとなく真ん中で対称な形をしてそうだが、なぜ？

### 残っている問題

- [x] FFTのグラフの高さになぜ差ができるのか？~振幅は各フーリエ成分で等しくしているので、グラフの高さに差ができるはずはない。~ Fourierすれば高さに差は出る。
- [x] 横軸の取り方の真相。真ん中で対称になっているのもヒントになるかもしれない。
- [x] 結局横軸を正しく取るにはどうすればいいのか。

**Comment by LowToneVoice** [comment]
実際に $\sin x + \sin 2x + \sin x/2+1$ をFourier級数展開すると $c_n=\frac{1}{2i}(\delta_{n,1}-\delta_{n,-1}+\delta_{n,2}-\delta_{n,-2}+\delta_{n,4}-\delta_{n,4})+\delta_{n,0}$ となるので、0成分だけ2倍になるので正しい

**Comment by LowToneVoice** [comment]
周期 $T$ に対して横軸は $\exp(2\pi inx/T)$ の $n\in\mathbb{Z}$ で周期的にとっているものと思われる。
特に実関数のFourier級数展開については、ampが0を中心に対称となるので、半分から左側を見れば十分。
この横軸を正しく取る i.e. $e^{ikx}$ の $k$ を持ってくるには、横軸の値に $2\pi/T$をかければいい。
tutorialで言っている $4\pi$ で割る操作は、 $2\pi$ を分離した振動数を求めるときに使う。
